"""
viz_hydra.py

This script is an entry point for visualizing the results of probabilistic model
inference runs in the SCRIBE framework. It is designed to be executed via Hydra,
a configuration management system, and expects as input a configuration file
describing the data, model, and inference parameters.

Key functionalities and workflow:

1. **Hydra Integration**:
   The script uses Hydra to manage configuration files. It is decorated with
   `@hydra.main`, which handles configuration parsing and working directory
   management, making it easy to reproduce results and manage output
   directories.

2. **Automatic Run Directory Resolution**:
   Based on the current Hydra configuration, the script reconstructs the path to
   the output directory that would have been generated by a prior model run.
   This ensures that visualizations access the correct results corresponding to
   the configuration parameters.

3. **Configuration Parsing**:
   The script extracts relevant information from the configuration (such as
   model type, inference method, parameterization, and data name). This data is
   used to standardize visualizations, plot filenames, and select results for
   plotting.

4. **Result Loading and Visualization**:
   While the full code (outside this docstring) handles result loading and
   plotting, the script delegates most of this functionality to a utility module
   (`viz_utils.py`). Functions like `plot_loss`, `plot_ecdf`, and `plot_ppc` are
   imported and then called to generate and save standardized figures—such as
   loss curves, ECDF plots, and posterior predictive checks—to the output
   directory.

5. **Error Checking**:
   If the expected run directory (from a previous inference job) does not exist,
   the script prints an error message and exits, prompting the user to first run
   inference.

6. **Extensibility**:
   The script is designed to be run as a standalone Hydra job, supporting
   extensions to additional plotting routines or diagnostics by simply updating
   `viz_utils.py` or the configuration files.

This structure helps users and downstream analysts quickly regenerate
standardized diagnostic and results visualizations—ensuring consistency,
reproducibility, and ease of use in SCRIBE model workflows.

Typical usage:
    $ python viz_hydra.py data=your_data_name inference=your_inference_method etc...

This will use Hydra to load the default or user-specified configuration,
auto-detect the corresponding results directory, and generate loss history,
ECDF, and posterior predictive check plots.
"""

import hydra
from omegaconf import DictConfig, OmegaConf
import scribe
import pandas as pd
import jax.numpy as jnp
import pickle
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scanpy as sc
import numpy as np
import warnings
from viz_utils import (
    _get_config_values,
    plot_loss,
    plot_ecdf,
    plot_ppc,
    plot_umap,
)

# Suppress scanpy/anndata deprecation warnings
warnings.filterwarnings("ignore", category=FutureWarning, module="scanpy")
warnings.filterwarnings("ignore", category=FutureWarning, module="anndata")

# ------------------------------------------------------------------------------


@hydra.main(version_base=None, config_path="conf", config_name="config")
def main(cfg: DictConfig) -> None:
    print("=" * 80)
    print("🎨 SCRIBE VISUALIZATION PIPELINE")
    print("=" * 80)
    print(f"📁 Working directory: {os.getcwd()}")
    print("\n📋 Configuration:")
    print("-" * 40)
    print(OmegaConf.to_yaml(cfg))

    # ==========================================================================
    # Directory Detection Section
    # ==========================================================================
    print("\n" + "=" * 80)
    print("🔍 DETECTING INFERENCE RESULTS")
    print("=" * 80)

    # Auto-detect the run directory based on the same Hydra path structure
    # that would have been used for the original inference run
    from hydra.core.hydra_config import HydraConfig

    hydra_cfg = HydraConfig.get()

    # Check if run_dir is explicitly set in viz config
    viz_cfg = getattr(cfg, "viz", None)
    if viz_cfg and hasattr(viz_cfg, "run_dir") and viz_cfg.run_dir != "???":
        run_dir = hydra.utils.to_absolute_path(viz_cfg.run_dir)
        print(f"📂 Using explicit run_dir from config: {run_dir}")
    else:
        # Construct the expected output directory path using the same logic as the
        # original config
        # This mirrors the hydra.run.dir pattern:
        # outputs/${data.name}/${inference.method}/${hydra:job.override_dirname}
        base_output_dir = "outputs"
        data_name = cfg.data.name
        inference_method = cfg.inference.method

        # Get the override dirname from current hydra config
        # Filter out viz.* parameters since they don't affect inference results location
        override_dirname = hydra_cfg.job.override_dirname
        if override_dirname:
            # Remove viz.* parameters from override_dirname
            override_parts = override_dirname.split(",")
            filtered_parts = [
                part
                for part in override_parts
                if not part.strip().startswith("viz.")
            ]
            override_dirname = (
                ",".join(filtered_parts) if filtered_parts else ""
            )

        # Construct the expected run directory
        run_dir = os.path.join(
            base_output_dir, data_name, inference_method, override_dirname
        )
        run_dir = hydra.utils.to_absolute_path(run_dir)

    print(f"🔍 Auto-detecting run directory...")
    print(f"📂 Expected directory: {run_dir}")

    # Check if the directory exists
    if not os.path.exists(run_dir):
        print("❌ ERROR: Run directory does not exist!")
        print(f"   Missing: {run_dir}")
        print(
            "💡 Make sure you've run the inference first with the same "
            "configuration."
        )
        return

    print("✅ Run directory found!")

    # ==========================================================================
    # Results Loading Section
    # ==========================================================================
    print("\n" + "=" * 80)
    print("📊 LOADING INFERENCE RESULTS")
    print("=" * 80)

    # Create figs directory
    figs_dir = os.path.join(run_dir, "figs")
    os.makedirs(figs_dir, exist_ok=True)
    print(f"📁 Figures directory: {figs_dir}")

    # Load scribe results
    results_file = os.path.join(run_dir, "scribe_results.pkl")
    print(f"📦 Loading results from: {results_file}")
    with open(results_file, "rb") as f:
        results = pickle.load(f)
    print("✅ Results loaded successfully!")

    # Load original config from the run directory
    orig_cfg_file = os.path.join(run_dir, ".hydra", "config.yaml")
    if not os.path.exists(orig_cfg_file):
        print("❌ ERROR: Original config file not found!")
        print(f"   Missing: {orig_cfg_file}")
        return

    print(f"📋 Loading original config from: {orig_cfg_file}")
    orig_cfg = OmegaConf.load(orig_cfg_file)
    print("✅ Original config loaded successfully!")

    # ==========================================================================
    # Data Loading Section
    # ==========================================================================
    print("\n" + "=" * 80)
    print("📊 LOADING ORIGINAL DATA")
    print("=" * 80)

    # Load data using the original config's data settings
    data_path = hydra.utils.to_absolute_path(orig_cfg.data.path)
    print(f"📂 Loading data from: {data_path}")
    counts = scribe.data_loader.load_and_preprocess_anndata(
        data_path, orig_cfg.data.get("preprocessing")
    )
    print(f"✅ Data loaded successfully! Shape: {counts.shape}")

    # ==========================================================================
    # Visualization Setup Section
    # ==========================================================================
    print("\n" + "=" * 80)
    print("🎨 VISUALIZATION SETUP")
    print("=" * 80)

    # Set plotting style
    print("🎨 Setting up matplotlib style...")
    scribe.viz.matplotlib_style()

    # Get visualization settings from current config or use defaults
    viz_cfg = getattr(cfg, "viz", None)
    if viz_cfg is None:
        # Use default visualization settings
        viz_cfg = OmegaConf.create(
            {
                "loss": True,
                "ecdf": True,
                "ppc": True,
                "format": "png",
                "ecdf_opts": {"n_genes": 25},
                "ppc_opts": {"n_genes": 25, "n_samples": 1500},
            }
        )
        print("⚙️  Using default visualization settings")
    else:
        print("⚙️  Using custom visualization settings")
        if hasattr(viz_cfg, "ppc_opts") and hasattr(
            viz_cfg.ppc_opts, "n_genes"
        ):
            print(f"   PPC n_genes: {viz_cfg.ppc_opts.n_genes}")

    # ==========================================================================
    # Plot Generation Section
    # ==========================================================================
    print("\n" + "=" * 80)
    print("📈 GENERATING PLOTS")
    print("=" * 80)

    plots_generated = []

    # --- Plotting functions will be called here based on viz config ---
    if viz_cfg.get("loss", True):
        print("📈 Generating loss history plot...")
        plot_loss(results, figs_dir, orig_cfg, viz_cfg)
        plots_generated.append("loss")

    if viz_cfg.get("ecdf", True):
        print("📊 Generating ECDF plot...")
        plot_ecdf(counts, figs_dir, orig_cfg, viz_cfg)
        plots_generated.append("ECDF")

    if viz_cfg.get("ppc", True):
        print("🔍 Generating posterior predictive check plots...")
        plot_ppc(results, counts, figs_dir, orig_cfg, viz_cfg)
        plots_generated.append("PPC")

    if viz_cfg.get("umap_opts", {}).get("enabled", False):
        print("🗺️  Generating UMAP projection plot...")
        plot_umap(results, counts, figs_dir, orig_cfg, viz_cfg)
        plots_generated.append("UMAP")

    # ==========================================================================
    # Completion Summary
    # ==========================================================================
    print("\n" + "=" * 80)
    print("🎉 VISUALIZATION COMPLETED SUCCESSFULLY!")
    print("=" * 80)
    print(f"📁 Results directory: {run_dir}")
    print(f"🎨 Figures directory: {figs_dir}")
    print(
        f"📊 Plots generated: {', '.join(plots_generated) if plots_generated else 'None'}"
    )
    print("=" * 80)


if __name__ == "__main__":
    main()
