# @package inference
# Variational Autoencoder configuration
# VAE uses SVI internally for optimization

method: vae

# SVI parameters used for VAE training
n_steps: 50_000
batch_size: null
stable_update: true

# VAE architecture (optional overrides)
# These are advanced options - defaults work well for most cases
# vae_latent_dim: 3
# vae_hidden_dims: [256, 256]
# vae_activation: gelu
